### ISSUE TITLE
Mirror doesn't load up

### ISSUE THREAD

**Issue by akshay068** [PoOwAa/MMM-network-signal#7]
My Mirror doesn't load up and if I remove the network-signal module part from config file - the mirror works fine. I have tried what was mentioned in issue #2 but no luck.

I get the following error while following the steps -

Error: Cannot find module 'ping'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-network-signal/node_helper.js:2:14)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-network-signal/node_helper.js:35:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module 'ping'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-network-signal/node_helper.js:2:14)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-network-signal/node_helper.js:35:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }

Thanks in advance

**Comment by PoOwAa** [comment]
The error says: `Cannot find module ping`. You missed the `npm i` part of the installation. When you put this module into your magic mirror (via cloning, or just simply copying the files), you have to install it's dependencies via `npm i` command.
